version: "3"
networks:
  net:
  default:
    external:
      name: bridge
services:
  generic: &node
    build:
      context: .
      dockerfile: Dockerfile
    networks: [net]
    entrypoint:
      - "ping"
      - "-i"
      - "60"
      - "1.1.1.1"
    volumes:
      - .:/export
  node1:
    << : *node
    networks: [default]
  node2:
    << : *node
    networks: [default]